#!/bin/bash

SELECTION="$(tmux list-windows -F '#{window_index}: #{window_name} - #{pane_title}' | fzf-tmux  -p 40%,30)" selection_res=$?

if [ $selection_res -eq 0 ]; then
    echo $SELECTION \
    | cut -d':' -f1 \
    | xargs -I {} tmux select-window -t {}
fi
