#!/bin/bash
if [ "$1" == "" ]; then
    SESSION=$(tmux list-sessions | sed -e 's/:.*//' | fzf-tmux --print-query 2>/dev/null | tail -1) 
    if [ "$SESSION" != "" ]; then
        tmux new -A -s $SESSION
    fi
else
    tmux new -A -s $1
fi
